/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "RoodbckPdfNew.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(RoodbckPdfNew); 

 RoodbckPdfNew::RoodbckPdfNew(const char *name, const char *title, 
                        RooAbsReal& _mbc,
                        RooAbsReal& _ebeam,
                        RooAbsReal& _alpha_mbc,
                        RooAbsReal& _alpha_de,
                        RooAbsReal& _de,
                        RooAbsReal& _de_mean,
                        RooAbsReal& _de_width,
                        RooAbsReal& _de_frac,
                        RooAbsReal& _mbc_mean,
                        RooAbsReal& _mbc_sigma0,
                        RooAbsReal& _mbc_sigma1,
                        RooAbsReal& _de_mean1,
                        RooAbsReal& _de_width1,
                        RooAbsReal& _de_frac1,
                        RooAbsReal& _mbc_mean1) :
   RooAbsPdf(name,title), 
   mbc("mbc","mbc",this,_mbc),
   ebeam("ebeam","ebeam",this,_ebeam),
   alpha_mbc("alpha_mbc","alpha_mbc",this,_alpha_mbc),
   alpha_de("alpha_de","alpha_de",this,_alpha_de),
   de("de","de",this,_de),
   de_mean("de_mean","de_mean",this,_de_mean),
   de_width("de_width","de_width",this,_de_width),
   de_frac("de_frac","de_frac",this,_de_frac),
   mbc_mean("mbc_mean","mbc_mean",this,_mbc_mean),
   mbc_sigma0("mbc_sigma0","mbc_sigma0",this,_mbc_sigma0),
   mbc_sigma1("mbc_sigma1","mbc_sigma1",this,_mbc_sigma1),
   de_mean1("de_mean1","de_mean1",this,_de_mean1),
   de_width1("de_width1","de_width1",this,_de_width1),
   de_frac1("de_frac1","de_frac1",this,_de_frac1),
   mbc_mean1("mbc_mean1","mbc_mean1",this,_mbc_mean1)
 { 
 } 


 RoodbckPdfNew::RoodbckPdfNew(const RoodbckPdfNew& other, const char* name) :  
   RooAbsPdf(other,name), 
   mbc("mbc",this,other.mbc),
   ebeam("ebeam",this,other.ebeam),
   alpha_mbc("alpha_mbc",this,other.alpha_mbc),
   alpha_de("alpha_de",this,other.alpha_de),
   de("de",this,other.de),
   de_mean("de_mean",this,other.de_mean),
   de_width("de_width",this,other.de_width),
   de_frac("de_frac",this,other.de_frac),
   mbc_mean("mbc_mean",this,other.mbc_mean),
   mbc_sigma0("mbc_sigma0",this,other.mbc_sigma0),
   mbc_sigma1("mbc_sigma1",this,other.mbc_sigma1),
   de_mean1("de_mean1",this,other.de_mean1),
   de_width1("de_width1",this,other.de_width1),
   de_frac1("de_frac1",this,other.de_frac1),
   mbc_mean1("mbc_mean1",this,other.mbc_mean1)
 { 
 } 



 Double_t RoodbckPdfNew::evaluate() const 
 { 
 
   if (mbc > ebeam) return 0;
   double dp_max = sqrt(ebeam*ebeam - mbc*mbc);
   if (fabs(0.1)<dp_max) {
     double p_mbc = exp(alpha_mbc*(mbc-ebeam)/ebeam);
     double p_de = exp(-alpha_de*de/1000.);

     double p_mbc2 = exp(-pow(mbc-mbc_mean,2)/2./mbc_sigma0/mbc_sigma0);
     double p_de2 = exp(-pow(de-de_mean,2)/2./de_width/de_width);

     double p_mbc3 = exp(-pow(mbc-mbc_mean1,2)/2./mbc_sigma1/mbc_sigma1);
     double p_de3 = exp(-pow(de-de_mean1,2)/2./de_width1/de_width1);

     return (p_mbc*p_de+fabs(de_frac)*p_mbc2*p_de2+fabs(de_frac1)*p_mbc3*p_de3)*dp_max;
   }
   return 0.;

 } 



