C********************************************************************
C    Include file with parameters for calculation
C          Phi -> a0 gamma -> eta pi0 gamma,
C       Phi -> f0 gamma -> pi0 pi0 gamma decays
C                         Al.Berdugin
C    13.04.98 V.Ivanchenko add Sigma parameters
C********************************************************************
C
       real *8       PhPhiA0,PhPhiF0,
     +               gF0KcKc,gF02Pi0,gF02Pi,
     +               gF02Eta,gF0EtaEtap,gF02Etap,
     +               gA0KcKc,gA0EtaPi,gA0EtapPi,
     +               MsSigma,GSigma,gSigma2Pi
C
       common/gR980a/PhPhiA0,PhPhiF0,
     +               gF0KcKc,gF02Pi0,gF02Pi,
     +               gF02Eta,gF0EtaEtap,gF02Etap,
     +               gA0KcKc,gA0EtaPi,gA0EtapPi,
     +               MsSigma,GSigma,gSigma2Pi
