#!/bin/bash
# -------------------------------------------
# --          use bash                     --
#$ -S /bin/bash
# -------------------------------------------
# --             batch name                --
#$ -N DmesonMC
# -------------------------------------------
# --     What to redirect to where         --
#$ -cwd
#$ -o /spool/users/ovtin/$JOB_NAME.o$JOB_ID
#$ -j y
# -------------------------------------------
# --             Enviroment                --
##$ -v PATH=$PATH:$HOME/release/KdRunFastMon,LD_LIBRARY_PATH=/usr/local/root/lib/root:/home/alexbarn/release/lib,KDBHOST=bison-2
# -------------------------------------------
# --             Queue list                --
##$ -soft
##$ -l time=24:00:00
##$ -q remote
##$ -q extralong
##$ -q 6h
#$ -q day
#$ -m beas
#$ -M ovtin.ivan@gmail.com

#$ -t 1-1

i=${SGE_TASK_ID}
myrand=$[1000+$i]

#start the job
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/simD0/mccards/mc.cards.ee_to_DD_"$i"
##kaon
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.k110
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.k200
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.k500
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.k800
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.k1200
##pion
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.pi110
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.pi200
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.pi500
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.pi800
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.pi1200
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.pi1500
##electron
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.e500
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.e800
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.e1200
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.e1500
##muon
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.mu110
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.mu200
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.mu500
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.mu800
##$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.mu1200
$HOME/development/bin/ks < $HOME/development/Dmeson/simulation/sim_mono/mc.cards.mu1500

status=$?
if [ $status != 0 ]; then
  echo "Program exited with status $status"
  exit
fi

echo "Job finished\n"

